#!/usr/bin/env python3
"""표준 원본에서 기존 CLI용 패키지를 생성한다. 생성물만 교체한다."""
import json
from pathlib import Path
import shutil
import tempfile

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "plugins/fullops-squad"
NATIVE = ROOT / "dist/native/fullops-squad"
STAMP = ".fullops-generated"


def write_json(path, value):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2) + "\n", encoding="utf-8", newline="\n")


def build(output=NATIVE):
    output = Path(output)
    if output.is_symlink() or (output.exists() and not (output / STAMP).is_file()):
        raise ValueError(f"빌드 생성물이 아닌 경로는 교체하지 않습니다: {output}")
    for path in SOURCE.rglob("*"):
        if path.is_symlink():
            raise ValueError(f"패키지 원본에 심볼릭 링크를 사용하지 마세요: {path}")
    manifest = json.loads((SOURCE / "plugin.json").read_text())
    mcp = json.loads((SOURCE / "mcp.json").read_text())
    native_mcp = {"mcpServers": {}}
    for name, server in mcp["mcpServers"].items():
        if server.get("type") != "stdio" or set(server) - {"type", "command", "args"}:
            raise ValueError(f"명시적인 호스트 변환이 필요한 MCP 설정: {name}")
        native_mcp["mcpServers"][name] = {k: v for k, v in server.items() if k != "type"}
    common = {key: manifest[key] for key in ("name", "version", "description", "author", "repository")}
    output.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix=".fullops-build-", dir=output.parent) as temp:
        staged = Path(temp) / "fullops-squad"
        shutil.copytree(SOURCE, staged, ignore=shutil.ignore_patterns("__pycache__", "*.pyc", ".git"))
        (staged / "mcp.json").unlink()
        shutil.copy2(ROOT / "dependencies.json", staged / "dependencies.json")  # 설치된 플러그인의 deps.py가 읽는다
        write_json(staged / "plugin.json", {key: common[key] for key in ("name", "version", "description")})
        for host, directory in (("codex", ".codex-plugin"), ("claude-code", ".claude-plugin")):
            adapter = json.loads((ROOT / f"adapters/{host}.json").read_text())
            if set(adapter) & set(common):
                raise ValueError(f"공통 메타데이터를 adapter에서 덮어쓸 수 없습니다: {host}")
            write_json(staged / directory / "plugin.json", {**common, **adapter})
        write_json(staged / ".mcp.json", native_mcp)
        write_json(staged / "mcp_config.json", native_mcp)
        (staged / STAMP).write_text("Generated by scripts/build.py; edit plugins/fullops-squad instead.\n", newline="\n")
        if output.exists():
            shutil.rmtree(output)
        staged.rename(output)
    return output


def update_catalogs():
    # 마켓플레이스 등록 경로는 유지하고 배포물의 source만 갱신한다.
    for relative in (".agents/plugins/marketplace.json", ".claude-plugin/marketplace.json"):
        path = ROOT / relative
        catalog = json.loads(path.read_text())
        for entry in catalog["plugins"]:
            if entry["name"] == "fullops-squad":
                source = "./dist/native/fullops-squad"
                entry["source"] = {"source": "local", "path": source} if relative.startswith(".agents/") else source
        write_json(path, catalog)


if __name__ == "__main__":
    print(build())
    update_catalogs()
